### ISSUE TITLE
This repository is over its data quota.

### ISSUE THREAD

**Issue by Gururajmetri118** [andre1araujo/YOLO-on-PYNQ-Z2#2]
Hi Andre,

I was planning to work on object detection on PYNQ-Z2 meanwhile, I found your git-hub. I found it very helpful, Thank You!

I'm writing an issue because I just came across an error log below: 
"**D:\YOLO-on-PYNQ-Z2>git lfs fetch
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/andre1araujo/YOLO-on-PYNQ-Z2.git/info/lfs'** "

So, I request you to help me out through this.

Thanks
Gururaj Metri

**Comment by andre1araujo** [comment]
Hello Gururaj!

Thank you very much for informing me about that issue. It turns out I used to much files and the set of LFS files exceeded the maximum of 1GB for the free account.
I removed some of them on the Auxiliary files folder and redirected the removed folders to a google drive in case anyone needs it. I am not sure if the problem is solved by now so I nedd you to try again and tell me if you can clone the repository successfully.
I am really sorry for the inconvenience and thank you again.

André

**Comment by andre1araujo** [comment]
Hi again Gururaj.

I tried cloning this repository and the error you described didn't appear. I think it is solved now.
I just need **your confirmation so I can close this issue**.
Is there anything more I can help you with? :)

Thank you!

**Comment by Gururajmetri118** [comment]
Hi Andre!

Sorry for the delay. I'm still facing the issue. 
I tried cloning the git repo, I got the below error:

**D:\git>git clone https://github.com/andre1araujo/YOLO-on-PYNQ-Z2.git
Cloning into 'YOLO-on-PYNQ-Z2'...
remote: Enumerating objects: 5907, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5907 (delta 0), reused 2 (delta 0), pack-reused 5903
Receiving objects: 100% (5907/5907), 265.96 MiB | 16.95 MiB/s, done.

Resolving deltas: 100% (425/425), done.
Updating files: 100% (5593/5593), done.
Downloading Auxiliary files/compilation/compile/dpu_yolo.elf (64 MB)
Error downloading object: Auxiliary files/compilation/compile/dpu_yolo.elf (ebfdc78): Smudge error: Error downloading Auxiliary files/compilation/compile/dpu_yolo.elf (ebfdc7853895d7bd4f8a5e71746d83ecb25d058352f534413f267502d0920f2d): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'D:\git\YOLO-on-PYNQ-Z2\.git\lfs\logs\20231215T101605.3238918.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Auxiliary files/compilation/compile/dpu_yolo.elf: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

D:\git>cd YOLO-on-PYNQ-Z2

D:\git\YOLO-on-PYNQ-Z2>git lfs fetch
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/andre1araujo/YOLO-on-PYNQ-Z2.git/info/lfs'**

Please, kindly help me out with this!

Thank you,
Gururaj Metri

**Comment by andre1araujo** [comment]
Hi again.

I'm sorry to inform that after spending all day trying to solve this problem, I couldn't reach a solution. After everything I tried to do, the git LFS storage kept the same. This might be actually *solvable* but I did everything I knew. I will try to make a new repository from scratch and direct some of the bigger files to a googledrive.
Thank you again and I am sorry for the inconvenience.

André
